# Generated by Django 3.2.6 on 2022-01-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Reactjs', 'Reactjs'), ('Php', 'Php'), ('Networking', 'Networking')], max_length=32)),
                ('pages', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
